const MESSAGE = {
  START: "START",
  NEW_MONSTER: "NEW_MONSTER",
  ATTACK_TO_MONSTER: "ATTACK_TO_MONSTER",
  ATTACK_TO_USER: "ATTACK_TO_USER",
  MONSTER_CLEAR: "MONSTER_CLEAR",
  GAME_OVER: "GAME_OVER",
}
